### ISSUE TITLE
Find new downsampling method to replace knor

### ISSUE THREAD

**Issue by eigenvivek** [neurodata-nomads/pymeda#4]
pymeda is difficult to install because of the dependency knor. however, knor is very useful because it is many orders of magnitude faster than alternative kmeans algorithms (such as sklearn's). therefore, it would be useful to find an alternative downsampling method that replace knor's primary function.

**Comment by jovo** [comment]
please clarify the problems you've been having with knor in the knorpy repo

**Comment by eigenvivek** [comment]
i personally have not been having any difficulties installing knor, but others on my team have. i will ask them what's up and open a new issue
